server:
  port: 5174
# DataSource Config
spring:
  application:
    name: matchProjection
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/team
  session:
    timeout: 86400  #session失效时间
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false #关闭驼峰映射逻辑
  global-config:
    db-config:
      logic-delete-field: idDeleted # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值