spring:
  application:
    name: matchProjection
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/team_prod
  session:
    timeout: 86400  #session失效时间